### ISSUE TITLE
show and save config details for idpBuilder tool

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#114]
The idpbuilder should allow its users to see and use configuration details for the deployed core technologies.

I am proposing we create a new command `idpbuilder config` that would do the following:

```bash
$ idpbuilder config
# pretty prints configuration details for all endpoints

$ idpbuilder config -o json
# prints configuration details for all endpoints in json
```

```json
{
  "argocd": {
    "url": "https://argocd.cnoe.localtest.me:8433",
    "username": "USERNAME",
    "password": "PASSWORD"
  },
  "gitea": {
    "url": "https://gitea.cnoe.localtest.me:8443",
    "username": "USERNAME",
    "password": "PASSWORD"
  },
  "backstage": {
    "url": "https://backstage.cnoe.localtest.me:8443",
    "username": "USERNAME",
    "password": "PASSWORD"
  }
}
```

specially given that the core set of idp tools are going to be small (Argo CD, Gitea, Backstage), a complete json list is probably very helpful to extract data from.

```bash
$ idpbuilder config gitea 
$ idpbuilder config argocd
... 
```

should print the config for a given tool and `-o json` should be available on them too. (output only)

```bash
$ idpbuilder config gitea -o json
```

```json
{
  "url": "https://gitea.cnoe.localtest.me:8443",
  "username": "USERNAME",
  "password": "PASSWORD"
}
```

Given the above, I think `--save` can save the config details for CLI use. 

For gitea it is rather straightforward, as it needs to populate a local git config with the following info

```
[credential "https://gitea.cnoe.localtest.me:8443/"]
        username = [USERNAME]
        password = [PASSWORD]
[http "https://gitea.cnoe.localtest.me:8443/"]
        sslVerify = false
```

For Argo CD, `idpbuilder config argocd --save` should make the credentials available to the argocd CLI.

For Backstage, it will probably be a noop.

/cc @cmollinard @nabuskey @blakeromano

**Comment by cmoulliard** [comment]
> a complete json list is probably very helpful to extract data from.

I prefer to show such output as a table by default

**Comment by cmoulliard** [comment]
> For Argo CD, `idpbuilder config argocd --save` should make the credentials available to the argocd CLI.

the config file of argocd is a bit different as it should get a token after issuying `argocd login`
-->
```
cat /Users/cmoullia/.config/argocd/config
contexts:
- name: argocd.cnoe.localtest.me:8443
  server: argocd.cnoe.localtest.me:8443
  user: argocd.cnoe.localtest.me:8443
current-context: argocd.cnoe.localtest.me:8443
servers:
- grpc-web: true
- grpc-web-root-path: ""
  insecure: true
  server: argocd.cnoe.localtest.me:8443
users:
- auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTcwMjczNzQ5NiwibmJmIjoxNzAyNjUxMDk2LCJpYXQiOjE3MDI2NTEwOTYsImp0aSI6IjQ4ZDRlOTczLWYzMGQtNGEwYS1hMjAyLTdhNTBmMmNmMDM1MyJ9.OhUSeNaJ3Dt6oArtKXnmUIptefiKP3iJlY3LxPE-BlM
  name: argocd.cnoe.localtest.me:8443
```
