### ISSUE TITLE
Configurable application port

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#139]
Currently, we listen on port 8443 for TLS traffic because the common 443 port is considered privileged and may not work for all users. This does not mean this value should be immutable. I think we should allow end users to customize this. 

We could possibly provide a new flag `--port`. When specified, it must change a few modifications. 

1. https://github.com/cnoe-io/idpbuilder/blob/5194086e5d2f087682d13ceb659d4b8433cee006/pkg/controllers/localbuild/gitea.go#L18
2. https://github.com/cnoe-io/idpbuilder/blob/5194086e5d2f087682d13ceb659d4b8433cee006/pkg/kind/resources/kind.yaml#L16

**Comment by cmoulliard** [comment]
2 ports should be configured: HTTP and HTTPS

For kind, that means ==> 
```
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```
**Remark**: Take also care that such ports should also be aligned with the Ingress Service manifest - https://github.com/cnoe-io/idpbuilder/blob/main/pkg/controllers/localbuild/resources/nginx/k8s/ingress-nginx.yaml#L353-L367
