### ISSUE TITLE
Support Kustomize with Custom Packages

### ISSUE THREAD

**Issue by greghaynes** [cnoe-io/idpbuilder#165]
Consider the case where an argo application is in a Kustomize package, and the user would like to create an overlay for local/CI which uses the cnoe:// format.

e.g.

`argocd/resources/application.yaml`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: github.com/myapp/config
    path: invalid
    targetRevision: main
```

`argocd/overlays/local`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: cnoe://../../../config/
```

and where `config/` is a directory of k8s resources we desire to install via our argo application.

If we were working with a normal argo application we would be able to specify repoUrl: `cnoe://../../config/` and pass that to idpbuilder, but because we need to run kustomize build beforehand this requires some extra, out-of-band file saving.
