### ISSUE TITLE
Add metric-server to ref-implementation

### ISSUE THREAD

**Issue by csantanapr** [cnoe-io/idpbuilder#198]
Closes #201 
Adding `metric-server` allows to debug problems with stacks
I was able debug the bug #197 by adding metric-server. 
On thing to take into account metric-server on kind needs to run with `--kubelet-insecure-tls`

Here is the argo app I used
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.12.1
    helm:
      releaseName: metrics-server
      values: |
        args:
        - --kubelet-insecure-tls
    chart: metrics-server
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

```
