### ISSUE TITLE
kubernetes secret "backstage-secrets" is missing

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#20]
## Issue

The deployment of bacckstage refers to a secret which is missing and blocks the deployment of backstage
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-12T07:16:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-12T07:16:38Z"
    message: 'containers with unready status: [backstage]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-12T07:16:38Z"
    message: 'containers with unready status: [backstage]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-12T07:16:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: public.ecr.aws/cnoe-io/backstage:v0.0.2
    imageID: ""
    lastState: {}
    name: backstage
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: secret "backstage-secrets" not found
        reason: CreateContainerConfigError
```
So the pod will crash using the image: `public.ecr.aws/cnoe-io/backstage:v0.0.2`
