### ISSUE TITLE
Backstage component is not deployed as service and no ingress route is available

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#22]
## Issue

The backstage component is not deployed as a service and no ingress route is published too
```
k get ingress -A
NAMESPACE          NAME                    CLASS   HOSTS                               ADDRESS     PORTS   AGE
argocd             argocd-server-ingress   nginx   argocd.idpbuilder.cnoe.io.local     localhost   80      10m
idpbuilder-local   gitserver-embedded      nginx   embedded.idpbuilder.cnoe.io.local   localhost   80      10m
```

**Comment by cmoulliard** [comment]
I included the following service and ingress yaml to the existing backstage yaml 
```
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7007
  - name: https
    port: 443
    protocol: TCP
    targetPort: 7007
  selector:
    app: backstage
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: backstage
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: backstage.idpbuilder.cnoe.io.local
      http:
        paths:
          - backend:
              service:
                name: backstage
                port:
                  name: https
            path: /
            pathType: Prefix
```
but cannot access the URL: 
```
curl -k http://backstage.idpbuilder.cnoe.io.local:8880/
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>

or

curl -k https://backstage.idpbuilder.cnoe.io.local:8443/
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```
