### ISSUE TITLE
[Feature] Enhance the command "idpbuilder get" 

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#226]
## Feature request

I like a lot the command "./idpbuilder get secrets" but it would be great if the command is also used to show more information the "package" and not only the credentials as this is the case today

```
 ./idpbuilder get secrets
---------------------------
Name: argocd-initial-admin-secret
Namespace: argocd
Data:
  password : nf0nCqUeN3iDPWI-
---------------------------
Name: gitea-admin-secret
Namespace: gitea
Data:
  password : ~by]1#1KF.:~?cSYP0Ns2-@*UO~X?0,[RIQ(4i8$
  username : giteaAdmin
```

So the existing command could be enhanced to provide such information
```
 ./idpbuilder get all
---
name: argocd
category: gitops
package-type: core // For custom packages the type will become: custom
namespace: argocd // Do we really need to report such a kubernetes namespace ?
spec:
  description: GitOps engine - see: doc url 
  url: https://argocd.cnoe.localtest.me:8443/
  credential:
    username: admin
    password : xxxxxxxxxxxx
---
name: git
category: git-source-management
package-type: core
namespace: gitea // Do we really need to report such a kubernetes namespace ?
spec:
  description: Git with a cup of tea - see: https://about.gitea.com/products/gitea/
  url: https://gitea.cnoe.localtest.me:8443/
  credential:
    username: giteaAdmin
    password : xxxxxxxxxxxx
---

or

./idpbuilder get <CORE_PACKAGE_NAME>

./idpbuilder get argocd
---------------------------
name: argocd-package
category: gitops
package-type: core
namespace: argocd // Do we really need to report such a kubernetes namespace ?
spec:
  description: GitOps engine - see: doc url 
  url: https://argocd.cnoe.localtest.me:8443/
  credential:
    username: admin
    password : x
```
