### ISSUE TITLE
[Bug]: Docker rate limit prevents install

### ISSUE THREAD

**Issue by danielguinan1** [cnoe-io/idpbuilder#229]
### What is your environment, configuration, and command?

Hi all, I'm trying this out after seeing it presented at DevOpsDays and I seem to be hitting an issue with docker's rate limit when running:
```
idpbuilder create --use-path-routing --package-dir examples/ref-implementation/
```
The cluster created and I can access resources via kubectl however it gets stuck on the gitea step due to the pull issue.
```
time=2024-04-26T10:51:28.677-07:00 level=INFO msg="Waiting for Deployment my-gitea to become ready" controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild Localbuild.name=localdev namespace="" name=localdev reconcileID=df97acad-4069-44c2-87ca-0e121d2c04fb
```

### What did you do and What did you see instead?

I logged into docker.io on the machine running the command and also manually pulled the images it backed off on, however no luck.  I would appreciate any insight on how I can add my credentials to the setup, or which manifests to edit for it.

Thanks

### Additional Information. Logs.

Builder Step:
```
time=2024-04-26T10:51:28.677-07:00 level=INFO msg="Waiting for Deployment my-gitea to become ready" controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild Localbuild.name=localdev namespace="" name=localdev reconcileID=df97acad-4069-44c2-87ca-0e121d2c04fb
```
example of pull error on `arggo-redis`
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  103s               default-scheduler  Successfully assigned argocd/argocd-redis-69f8795dbd-hmlp9 to localdev-control-plane
  Warning  Failed     54s (x3 over 92s)  kubelet            Failed to pull image "redis:7.0.14-alpine": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/redis:7.0.14-alpine": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/redis/manifests/sha256:45de526e9fbc1a4b183957ab93a448294181fae10ced9184fc6efe9956ca0ccc: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     54s (x3 over 92s)  kubelet            Error: ErrImagePull
  Normal   BackOff    16s (x5 over 92s)  kubelet            Back-off pulling image "redis:7.0.14-alpine"
  Warning  Failed     16s (x5 over 92s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    1s (x4 over 102s)  kubelet            Pulling image "redis:7.0.14-alpine"

**Comment by nabuskey** [comment]
Sounds like you are hitting the DockerHub rate limit. Are you authenticated with DockerHub? They give you higher limits if you do. As far as I am aware, I don't think there's anything we can do on our side other than possibly hosting them on our own registry. 

https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by danielguinan1** [comment]
@nabuskey Yes I'm logged in to docker hub on the box running the command and can pull images, though it seems like it doesn't transfer that login session into the container.  Since there isn't a global pull secret on kube I'm thinking I may have to create a pull secret in every namespace and edit the resources to use it.  

Would this be possible or does ArgoCD control these resources as well causing them to revert back? Also would this manual edit break anything if the change is made while `idpbuilder create` command is running?

**Comment by nabuskey** [comment]
Oh I read that wrong sorry. I thought it was coming from puling kind image. 

Since the underlying cluster is provisioned is kind, we should follow their guides. Easiest way is to do this with kind configuration. https://kind.sigs.k8s.io/docs/user/private-registries/#mount-a-config-file-to-each-node

You just have to make sure the kubelet has access to your credentials.

You can supply the kind config file like so: `idpbuilder create --kind-config <PATH_TO_CONFIG>`
Something like this should work ( I haven't tested this) :
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: "kindest/node:v1.27.3"
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: /path/to/my/secret.json # replace with your own path
    extraPortMappings:
      - containerPort: 443
        hostPort: {{ .Port }}
        protocol: TCP
```
