### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#28]
Currently tests are broken. Need to fix them.

An example failed run
https://github.com/cnoe-io/idpbuilder/actions/runs/6532866095/job/17750266601

#36

**Comment by cmoulliard** [comment]
The problem is related to this error `registry_test.go:31: Error reconciling registry: Error response from daemon: network kind not found`

**Comment by cmoulliard** [comment]
Controller_test fails as content compared diverges from the existing kind config
```
/opt/homebrew/opt/go/libexec/bin/go tool test2json -t /Users/cmoullia/Library/Caches/JetBrains/IntelliJIdea2023.2/tmp/GoLand/___cluster_test_go.test -test.v -test.paniconexit0 -test.run ^\QTestGetConfig\E$
=== RUN   TestGetConfig
    cluster_test.go:55: Got config: # two node (one workers) cluster config
        # Kind kubernetes release images https://github.com/kubernetes-sigs/kind/releases
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        containerdConfigPatches:
        - |-
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
            endpoint = ["http://idpbuilder-testcase-registry:5000"]
        nodes:
        - role: control-plane
          image: "kindest/node:v1.26.3"
          kubeadmConfigPatches:
          - |
            kind: InitConfiguration
            nodeRegistration:
              kubeletExtraArgs:
                system-reserved: memory=4Gi
                node-labels: "ingress-ready=true"
          extraPortMappings:
          - containerPort: 80
            hostPort: 8880
            protocol: TCP
          - containerPort: 443
            hostPort: 8443
            protocol: TCP
          -
        - role: worker
          image: "kindest/node:v1.26.3"
          kubeadmConfigPatches:
          - |
            kind: JoinConfiguration
            nodeRegistration:
              kubeletExtraArgs:
                system-reserved: memory=4Gi
```
