### ISSUE TITLE
[Bug]: All occurrences of cnoe:// not getting replace everywhere

### ISSUE THREAD

**Issue by csantanapr** [cnoe-io/idpbuilder#339]
### What is your environment, configuration, and command?

latest version

### What did you do and What did you see instead?

I'm building a helm chart that acts like an app of applicationsets and I need to pass down the repoURL down to the helm chart

I have the following app, but only one occurence of cnoe:// gets replace
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  source:
    repoURL: cnoe://addons
    path: "charts/gitops-bridge"
    helm:
      valuesObject:
        repoURLGit: cnoe://addons
        repoURLValues: cnoe://addons
        applicationsets:
          argocd:
            enabled: false
          aws_load_balancer_controller:
            enabled: false
          gatekeeper:
            enabled: true
  project: default
  syncPolicy:
    automated:
      selfHeal: true
```
As workaround I have to hardcoded the values like this
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: "in-cluster"
  source:
    repoURL: cnoe://addons
    path: "charts/gitops-bridge"
    helm:
      valuesObject:
        repoURLGit: https://gitea.cnoe.localtest.me:8443/giteaAdmin/idpbuilder-localdev-addons-addons.git
        repoURLValues: https://gitea.cnoe.localtest.me:8443/giteaAdmin/idpbuilder-localdev-addons-addons.git
        applicationsets:
          argocd:
            enabled: false
          aws_load_balancer_controller:
            enabled: false
          gatekeeper:
            enabled: true
  project: default
  syncPolicy:
    automated:
      selfHeal: true
```
