### ISSUE TITLE
[Suggestion] Remove the hard coded ingress yaml resources to use instead a helm chart deployed using argoCD

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#34]
## Suggestion

Remove the hard coded ingress yaml resources to use instead a helm chart deployed using argoCD

## How to reproduce
- Remove as embedApps -> ingress-nginx [here](https://github.com/cnoe-io/idpbuilder/blob/56089e4ae3b27cf90641bfbff2a96c36dd5263e1/pkg/apps/resources.go#L29-L32)
- Run `make`
- Create a new cluster `./idpbuilder create --buildName local --recreate`
- Create a helm values file and deploy the ingress controller helm chart
```
cat <<EOF > values.yaml
controller:
  allowSnippetAnnotations: true
  service:
    type: NodePort
  hostPort:
    # Use host ports 80 and 443
    enabled: true
  watchIngressWithoutClass: true
  extraArgs:
    enable-ssl-passthrough: ""
  nodeSelector:
    # This selector is needed as it has been declared as kind kubeletExtraArgs => node-labels: "ingress-ready=true"
    ingress-ready: "true"
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Equal
EOF

helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx  --create-namespace -f values.yaml
```
- Check in your browser that you can access the argoCD UI: `https://argocd.idpbuilder.cnoe.io.local:8443/`

## Next step

Replace the Helm command with an Application CR. Something like (NOT TESTED):
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-helm
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.2
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          allowSnippetAnnotations: true
          service:
            type: NodePort
          hostPort:
            # Use host ports 80 and 443
            enabled: true
          watchIngressWithoutClass: true
          extraArgs:
            enable-ssl-passthrough: ""
          nodeSelector:
            # This selector is needed as it has been declared as kind kubeletExtraArgs => node-labels: "ingress-ready=true"
            ingress-ready: "true"
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Equal
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Equal
  project: idpbuilder-embedded-gitserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
