### ISSUE TITLE
[Bug]: Validate and ensure the container port we need is available and correct. 

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#358]
### What is your environment, configuration, and command?

If you run idpbuilder without the necessary container port defined, it will never finish reconciling because we can't talk to the gitea service. We need to ensure:

- Correct port is exposed EVEN IF user supplied kind config does not specify it.
- Make sure we print it out.

Kind config to reproduce the issue: 

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ~/.docker/config.json
    extraPortMappings:
      - containerPort: 31337
        hostPort: 31337
      - containerPort: 31340
        hostPort: 31340
      - containerPort: 31333
        hostPort: 31333
```

### What did you do and What did you see instead?

idpbuilder never finishes reconciling.
