### ISSUE TITLE
Document passing credentials to pull from private registries

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#393]
Steps are described here. https://github.com/cnoe-io/idpbuilder/issues/229

For ECR:

```bash
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 1111.dkr.ecr.<REGION>.amazonaws.com
idpbuilder create --recreate --kind-config kind-registry.yaml

```
kind yaml:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: "kindest/node:v1.30.0"
  labels:
    ingress-ready: "true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /home/ubuntu/.docker/config.json

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gitea.cnoe.localtest.me:8443"]
    endpoint = ["https://gitea.cnoe.localtest.me"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."gitea.cnoe.localtest.me".tls]
    insecure_skip_verify = true
```
