### ISSUE TITLE
Improve how we name the girepository and custompackage resources

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#470]
## Enhancement

When a new cluster is created and a package added, then the `gitRepository` and `custompackage` resources like the gitea url name includes twice the same name if by example the name of the YAML file and the name of the Argocd resource uses both the same name.

Example:

If we install the following package `-p /Users/cmoullia/code/ch007m/my-konflux/fork-konflux-ci/idp/foundations/` which contains several Argocd files as showed hereafter

```
foundation/
  cert-manager/
  cluster-issuer/
  test-pvc/
  trust-manager/

  cert-manager.yaml
  cluster-issuer.yaml
  test-pvc.yaml
  trust-manager.yaml
```

then the file name `cluster-issuer.yaml` and the Argocd Application name which is `cluster-issuer` will be used to name the customPackage and gitRepository YAML resources

```
apiVersion: idpbuilder.cnoe.io/v1alpha1
kind: CustomPackage
metadata:
  name: cluster-issuer-cluster-issuer
  namespace: idpbuilder-dummy
...

apiVersion: idpbuilder.cnoe.io/v1alpha1
kind: GitRepository
metadata:
  name: cluster-issuer-cluster-issuer
  namespace: idpbuilder-dummy
```

and urls will be:
```
https://gitea.cnoe.localtest.me:9443/giteaAdmin/idpbuilder-dummy-cluster-issuer-cluster-issuer
https://argocd.cnoe.localtest.me:9443/applications/argocd/cluster-issuer
```

While this is not an issue per se, that could hurt some users as it is hard to figure out that the package `-p .../foundations` match several components = argocd applications and that the resources created on the platform don't include the name of the package (= last word of `a/b/c/d` string) AND why name could appear twice.

This is why I would like to propose that we adopt a new convention (which is also perhaps not perfect too) but a bit better to name the resources like the git internal repository and which could address the proposition to have a command able to add/remove a customPackage (see #469)

Convention:
- We extract the last word from the package path.
   ```
   -p  foundations => foundations 
   -p  idp/foundations => foundations 
   -p ~/code/ch007m/my-konflux/fork-konflux-ci/idp/foundations => foundations
   -p ~/code/ch007m/my-konflux/fork-konflux-ci/idp/foundations/cluster-issuer.yaml => foundations
   ```
- We iterate within the list of the Argocd files and for each item, get the Application(Set) name
  ```
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: cluster-issuer // Name to be used
    namespace: argocd
  ```
- We concatenate the package name with the argocd application name and we use the symbol `-` as separator
  ```
  foundations-cluster-issuer
  ```

If we do that, then the new name will become:
```
apiVersion: idpbuilder.cnoe.io/v1alpha1
kind: CustomPackage
metadata:
  name: foundations-cluster-issuer
  namespace: idpbuilder-dummy
...

apiVersion: idpbuilder.cnoe.io/v1alpha1
kind: GitRepository
metadata:
  name: foundations-cluster-issuer
  namespace: idpbuilder-dummy
...

https://gitea.cnoe.localtest.me:9443/giteaAdmin/idpbuilder-dummy-foundations-cluster-issuer
or
https://gitea.cnoe.localtest.me:9443/giteaAdmin/foundations_cluster-issuer.git

https://argocd.cnoe.localtest.me:9443/applications/argocd/cluster-issuer
```
**Remarks**: 
- We could even use the `underscore` within the git url to make a clear separation between the `package` name and the component/repository
- I don't think that it makes a lot of sense to also prefix a git repository with the namespace name `idpbuilder-<cluster-name>`
