### ISSUE TITLE
Setup Go Releaser

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#50]
We should setup a Release GitHub action. This should be invoked when a new tag in the form `v*.*.*` is pushed. 

Something like:

```
name: go-releaser
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> 1.20.0'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
