### ISSUE TITLE
[Suggestion] Create only one kubernetes node and not two as this is the case today: worker and control plane

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#54]
## Issue

idpbuilder deploys, when it starts, a kubernetes worker node and control plane node where worker don't expose ports. As some pods such as: ingress, gitea, etc should be deployed on the docker container exposing the ports: 8880, 8443, 22 or 2222 to access them from the host, it is needed to define on the Deployment resource, a nodeSelector and Tolerations

```
          nodeSelector:
            ingress-ready: "true"
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Equal
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Equal
```

As this is not needed to use 2 separate nodes, that such configuration makes the work more harder for the user to hack the Helm configuration of the Deployment and maintainer I suggest to revert the kind definition to only setup one container/node like this:
```
# two node (one workers) cluster config
# Kind kubernetes release images https://github.com/kubernetes-sigs/kind/releases
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:{{ .ExposedRegistryPort }}"]
    endpoint = ["http://{{ .RegistryHostname }}:{{ .InternalRegistryPort }}"]
nodes:
- role: control-plane
  image: "kindest/node:v1.26.3" // WE SHOULD OFFER TO THE USER A PARAMETER TO OVERRIDE THE HARD CODED KUBERNETES VERSION
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=4Gi
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8880
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 32222 // EXTRA PORT TO BE DEFINED AS COMMAND LINE PARAMETER
    hostPort: 22 // EXTRA PORT TO BE DEFINED AS COMMAND LINE PARAMETER
    protocol: TCP
```

**REMARK**: We should also offer the possibility when we execute `./idpbuilder create` to specify extraPorts as needed by some components/packages (e.g gitea containerPort 22 -> nodePort 32222)

See: https://cloud-native.slack.com/archives/C05TN9WFN5S/p1697818908286999
