### ISSUE TITLE
API type for Git repository

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#59]
The new type is used to reconcile git repositories. 

Given a ArgoCD application spec like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
    - path: argo-workflows
      repoURL: "files://test-package"
      targetRevision: HEAD
```

idpbuilder should:
1. Create a new repository in the in-cluster git server. 
2. Populate the repository with the contents from the local `test-package` directory. 
3. Update the `repoURL` field(s) to the URL from step 1. 
4. Set the source type to 'directory'
5. Any changes to this directory should be synced during reconciliation. 

API type may look something like

```go
type GitRepositorySpec struct {
	Source GitRepositorySource `json:"source,omitempty"`
}

type GitServerSource struct {
	Directory string `json:"directory"`
        // +kubebuilder:validation:Enum:=dir,remote
        Type string `json:"type"`
        // +kubebuilder:validation:Enum:=helm,kustomize,manifests
        // +kubebuilder:default:=manifests
        Format string `json:"format"`
}

```
