### ISSUE TITLE
Add issue templates for questions, enhacement requests, and PRs.

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#62]
Something like

```yaml
name: Feature
description: Provide supporting details for a feature in development
title: "[Feature]: <title>"
labels: ["enhancement"]
  - type: textarea
    id: feature
    attributes:
      label: Feature description
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true

```
